# Generated by Django 5.1.4 on 2024-12-23 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0007_ban_qr_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='KhuyenMai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tenkm', models.CharField(max_length=255, verbose_name='Tên khuyến mãi')),
                ('makm', models.CharField(max_length=10, verbose_name='Mã khuyến mãi')),
                ('phantram', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Phần trăm giảm giá')),
                ('tinhtrang', models.CharField(choices=[('active', 'Còn'), ('inactive', 'Hết')], default='inactive', max_length=10, verbose_name='Tình trạng')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='khuyen_mai',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rm.khuyenmai'),
        ),
    ]
