# Generated by Django 5.1.4 on 2024-12-23 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0008_khuyenmai_order_khuyen_mai'),
    ]

    operations = [
        migrations.AlterField(
            model_name='khuyenmai',
            name='phantram',
            field=models.DecimalField(decimal_places=0, max_digits=5, verbose_name='Phần trăm giảm giá'),
        ),
    ]
