# Generated by Django 5.1.4 on 2024-12-14 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lichlamviec',
            name='trangthai_nhanvien',
            field=models.BooleanField(default=False),
        ),
    ]
