# Generated by Django 5.1.4 on 2024-12-15 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0002_lichlamviec_trangthai_nhanvien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lichlamviec',
            name='trangthai_nhanvien',
            field=models.CharField(choices=[('chua_vaoca', 'Chưa vào ca'), ('trong_ca', 'Đang trong ca'), ('ra_ca', 'Đã ra ca')], default='chua_vaoca', max_length=20),
        ),
    ]
