# Generated by Django 5.1.4 on 2024-12-16 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0003_alter_lichlamviec_trangthai_nhanvien'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='chi_phi',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Chi phí'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='gia',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Giá'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='mota',
            field=models.CharField(choices=[('starter', 'Khai vị'), ('main', 'Món chính'), ('dessert', 'Tráng miệng')], default='main', max_length=50, verbose_name='Loại món'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='ten',
            field=models.CharField(max_length=100, verbose_name='Tên món ăn'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='tinhtrang',
            field=models.BooleanField(default=True, verbose_name='Trạng thái'),
        ),
    ]
