# Generated by Django 5.1.4 on 2024-12-17 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0004_alter_menu_chi_phi_alter_menu_gia_alter_menu_mota_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chitietorder',
            name='gia',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='menu',
            name='chi_phi',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Chi phí'),
        ),
        migrations.AlterField(
            model_name='menu',
            name='gia',
            field=models.DecimalField(decimal_places=0, max_digits=10, verbose_name='Giá'),
        ),
    ]
