# Generated by Django 5.1.3 on 2024-12-18 04:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0005_alter_chitietorder_gia_alter_menu_chi_phi_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customuser',
            managers=[
            ],
        ),
    ]
