# Generated by Django 5.1.4 on 2024-12-23 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rm', '0006_alter_customuser_managers'),
    ]

    operations = [
        migrations.AddField(
            model_name='ban',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
